version: 2
jobs:
  test:
    docker:
      - image: cimg/node:17.1.0-browsers
        auth:
          username: saicharanj
          password: Saicharan@501  # context / project UI env-var reference
    parallelism: 4
