version: 2
jobs:
  test:
    docker:
      - image: cimg/<language>:<version TAG>
        auth:
          username: saicharanj
          password: Saicharan@501  # context / project UI env-var reference
    parallelism: 4
